export const PALABRAS: string[] = [
    "ELEFANTE", "CUCHARA", "BICICLETA", "MARIPOSA", "CATEDRAL",
    "MONTANA", "PERRO", "ASTRONAUTA", "CAMISETA", "MURCIELAGO",
    "PINGUINO", "CAMIONETA", "VENTILADOR", "COMPUTADORA", "ALFOMBRA",
    "JIRAFA", "PINTURA", "TELEFONO", "REFRIGERADOR", "COHETE",
    "ESPEJO", "BOTELLA", "CARAMELO", "ESCRITORIO", "MOCHILA",
    "MARTILLO", "DESTORNILLADOR", "HOSPITAL", "BUZO", "PESCADOR",
    "TECLADO", "RATON", "PARAGUAS", "AVION", "NUBE",
    "TRAVESIA", "GLOBO", "CACTUS", "CAJA", "SILLA",
    "TIGRE", "ZORRO", "LAMPARA", "ALMOHADA", "TOMATE",
    "LECHUGA", "ZANAHORIA", "ARANDANO", "FRUTILLA", "BANANA",
    "NARANJA", "MANZANA", "SANDIA", "LIMON", "COCHE",
    "CAMION", "TRACTOR", "BARCO", "SUBMARINO", "CUERDA",
    "TIJERA", "PEGAMENTO", "LIBRETA", "CUADERNO", "BRUJA",
    "HECHIZO", "MAGO", "POCION", "DRAGON", "CASTILLO",
    "REY", "PRINCESA", "ESPADA", "ARMADURA", "SOLDADO",
    "POLICIA", "BOMBERO", "MAESTRO", "DENTISTA", "COCINERO",
    "PANADERO", "MECANICO", "ELECTRICISTA", "CARTERO", "DOCTOR",
    "INGENIERO", "ARQUITECTO", "FOTOGRAFO", "CANTANTE", "GUITARRA",
    "PIANO", "TROMPETA", "VIOLIN", "TAMBOR", "BANDERA",
    "ESCUELA", "UNIVERSIDAD", "PUERTA", "VENTANA", "ESCUADRA"
];
  